import Foundation

enum ConfigWriter {
    static func write(config: VPNConfiguration, credentials: Credentials) throws -> URL {
        var lines: [String] = [
            "# Generated by SSLVPNAutoConnect — do not edit while connected",
            "host = \(config.host.trimmingCharacters(in: .whitespacesAndNewlines))",
            "port = \(config.port)",
            "username = \(credentials.username.trimmingCharacters(in: .whitespacesAndNewlines))",
            "password = \(credentials.password)",
            "set-dns = \(config.setDNS ? 1 : 0)",
            "set-routes = \(config.setRoutes ? 1 : 0)",
            "pppd-use-peerdns = \(config.setDNS ? 1 : 0)",
            "use-syslog = 0",
        ]

        if config.persistentInterval > 0 {
            lines.append("persistent = \(config.persistentInterval)")
        }

        let cert = config.trustedCert.trimmingCharacters(in: .whitespacesAndNewlines)
        if !cert.isEmpty {
            lines.append("trusted-cert = \(cert)")
        }

        let realm = config.realm.trimmingCharacters(in: .whitespacesAndNewlines)
        if !realm.isEmpty {
            lines.append("realm = \(realm)")
        }

        let content = lines.joined(separator: "\n") + "\n"
        let url = AppPaths.configFile

        try content.write(to: url, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)

        return url
    }

    static func removeConfig() {
        try? FileManager.default.removeItem(at: AppPaths.configFile)
    }
}
